# Generated by Django 4.0.4 on 2022-04-24 14:17

from django.db import migrations, models

import purchase.models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="display_order",
            field=models.PositiveIntegerField(
                default=purchase.models.default_product_display_order,
            ),
        ),
    ]
