# Generated by Django 4.0.4 on 2022-04-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0003_alter_product_display_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="status",
        ),
    ]
