# Generated by Django 4.0.4 on 2022-05-05 16:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_alter_basketitem_unit_price_cents"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="basketitem",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("product"),
                django.db.models.expressions.F("basket"),
                name="unique_product_per_basket",
            ),
        ),
    ]
