# Generated by Django 4.1.1 on 2022-09-25 19:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0008_basketitem_unique_product_per_basket"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketItemEtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
