# Generated by Django 4.1.1 on 2022-09-25 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0009_basketitemetag"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BasketItemEtag",
            new_name="CacheEtag",
        ),
    ]
