# Generated by Django 4.1.7 on 2023-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0012_rename_value_cache_etag_cache_last_modified"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="basketitem",
            name="unique_product_per_basket",
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price_cents",
            field=models.PositiveIntegerField(
                help_text="Unit price in cents. Use zero to denote that the product has no fixed price.",
                verbose_name="unit price (cents)",
            ),
        ),
    ]
