# Generated by Django 4.1.7 on 2023-04-02 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0015_remove_product_image_product_initials"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ("name",),
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
    ]
