# Generated by Django 4.1.7 on 2023-04-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0017_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchase.productcategory",
                verbose_name="category",
            ),
            preserve_default=False,
        ),
    ]
