# Generated by Django 4.2.8 on 2024-01-20 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0018_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
            },
        ),
    ]
