name: Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-sync requirements.txt requirements-dev.txt
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gettext
      - name: Setup pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Check pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Test
        run: inv test-cov
        working-directory: ./src/
